### PR TITLE
Iss9

### PR DESCRIPTION
**Pull request by ericchansen**
Speak now or forever hold your peace. Also, someone please sign off on this.

### CODE REVIEW

**Comment by peonor** [comment]
I guess I have to speak with Tony on how to do this. I’ve followed all the links and tried to look at all active items, don’t see any way to “sign off”.

I also don’t understand why you have to wait for one of us to do this? Maybe a discussion I missed, but I don’t see this as a symmetric situation. You’re the boss on this one, don’t see that you should have to wait. But it does make perfect sense to me that no one else should upload something before you OK’ed it.

I’m starting to get the feel for doing some things in git, but I’m still not sure what happens/what the difference is between the different commands, like commit, merge, push, stash, … I’ll find some “git for dummies”, the ones I’ve encountered so far seem to be for Windows, a bit different from what I need to do.

/Per-Ola

**Comment by arosale4** [comment]
Only people with write access can confirm a merge, or commit. So only you, Eric, can do this because we are talking about ericchansen/q2mm.

**Comment by ericchansen** [comment]
Tony is right. Please stop reporting issues here (we have already discussed this and decided to report issues on [q2mm/q2mm](https://github.com/Q2MM/q2mm/issues)).

Also, the reason we are waiting for pulls is so people can double check me. I make plenty mistakes, especially when I am making changes for you guys that have no effect on my systems. I also don't have time or resources to test thoroughly enough in cases like this.

**Comment by peonor** [comment]
OK, but then I’ll download the Q2MM/q2mm code instead, and work from that from now on. Tony, should you do the same?

/Per-Ola

**Comment by ericchansen** [comment]
This is how I work.

Clone q2mm/q2mm or ericchansen/q2mm. I like a folder for development, so I name it as such.

```
git clone https://github.com/q2mm/q2mm/ q2mm_dev
```

Add the other remote so you can access both.

```
git remote add other https://github.com/ericchansen/q2mm/
```

Modify .git/config and change the url lines under remote from
```
url = https://github.com/ericchansen/q2mm/
```

to

```
url = https://ericchansen@github.com/ericchansen/q2mm/
```

Then I do a fetch so I can work with everything.

```
git fetch --all
```

Here's q2mm/master.

```
git checkout master
```

Here's ericchansen/master.

```
git checkout other/master
```

Say I make a branch myhotfix.

```
git checkout -b myhotfix
````

Make some changes

```
emacs ...
git commit
```

and then I can push to q2mm/q2mm

```
git push origin myhotfix
```

or to ericchansen/q2mm

```
git push other myhotfix
```

**Pull request closed without merging**
