### PR TITLE
Many changes to help with issue #22

### PR DESCRIPTION
**Pull request by ericchansen**
Lots of helpful changes inside here.

Still need to do testing before going forward. Here's some things to consider.

1. Is simplex reading the estimated derivatives properly from gradient?
1. How best to handle raise when all trial parameter sets produce the same objective function score.
1. If simplex follows gradient, should simplex only act on parameters with negative 2nd derivatives? Would simplex do nothing if no parameter has a negative 2nd derivative? Or would we rather keep it the same and have it act on which parameters have the lowest 2nd derivatives, not necessarily negative?
1. If the user wants to run only simplex and specifies more parameters, than the maximum parameter number set inside `simplex.Simplex.__init__`, do we want to let them use that number of parameters or should it check the 2nd derivatives?

### CODE REVIEW

**Comment by peonor** [comment]
I have thought on these. Answering each in turn:


1.       In my code (before Elaines), I would, after the numerical differentiation, have the Jacobian on file (my old par.tot), and in the log list the explicit 1st and 2nd derivatives of the penalty function with respect to each parameter. That information would help a lot in analyzing this. I may get around to inserting that myself, but want to get more comfortable with the logger first.

2.       In this case, the Simplex should be considered converged. We may consider even quitting early whenever the worst and best point become similar (for example, (worst score)/(best score) < 1.1 ). The 1.1 here could well be a user-defined variable, or we might want to give it as “differ by less than 10%” or something.

3.       This is not an easy question, really. Candidates for Simplex should be all with negative 2nd derivative, but also all where the 1st derivative is large compared to the 2nd; both of those cases would be expected to be handled badly by the matrix methods. If we call the 1st derivative D’ and the 2nd D”, we could calculate a sort of matrix suitability index as D”/(D’)^2, sort according to that index (putting all large negative D” first), and then just pick from the bottom until we reached 10, or put a threshold also (maybe simply “+1”), and exclude all parameters above the threshold, so we could end up with fewer than 10. However, we should always have a minimum of 2 parameters, maybe 3, it makes no sense to run a single-parameter Simplex (even though I’d prefer the code to be stable to it).

4.       If you do NOT run a gradient first, then we should ignore max_param and let the use specify all the parameters they wish. The max_param has been there only to use in conjunction with gradient.

One question: when you refer to “the old code”, do you mean the python code from Elaine (which was never fully tested), or the much more thoroughly tested collection of C and Unix scripts (no python) that I had been using for 15 years before Elaine started? I know you found errors in the C-code, and it was extremely user-unfriendly, but still, it was more reliable, and had functionality that we still lack in your code. And that’s really the only code I can answer about, I never fully got into Elaines.

/Per-Ola

**Comment by ericchansen** [comment]
In that particular reference, I was talking about the Elaine's Python code. Some things I remember better from her Python scripts, some things I remember better from the C source code.

All your recommendations in regards to my list seem good. I will do what I can to get these all addressed, starting with the strange, probably buggy simplex behavior you mentioned in previous comments and emails.

**Comment by peonor** [comment]
At least in the code I’m playing with now, only the parameter selection seems to be a problem. I’ve followed it in detail through a number of cycles now where I simply gave it the correct number of parameters, and it now behaves exactly like I want, as long as I don’t give it >10 parameters.

One remaining difference with my old code; I had taken away the massive contraction completely, the alternative is simply to accept the contraction value whatever it is and continue (which is what my own code would do; that part was not in C, but in my awkward Unix/awk combo). An intermediate possibility would be to say massive contraction after a certain number of failed contractions (failed being defined as never getting past the 2nd worst value). And the number of allowed failures could, for example, be the same as the number of parameters, or a fixed value like 3. Lot’s of possibilities. Lets postpone them, but you can think about them if you want.

I had forgotten how detailed I was about the simplex in the 1998 paper. If we go by that, we should definitely allow subset optimizations with only simplex and a large number of variables. We did recommend 30-40, so let’s not limit the user in a Simplex-only optimization.

/Per-Ola

**Comment by ericchansen** [comment]
You can turn massive contraction off for now by changing `self.do_massive_contraction` to `False` inside `__init__`. Those other ideas are all reasonable too. Like you said, we can pick one later.

**Pull request merged**
